SystemUI: do not load header bar if boot isn't complete
Sometimes during OOBE this header bar will bind the search widget
before boot is complete. This will cause a force close due to:
java.lang.IllegalStateException: Cannot broadcast before boot completed

CYNGNOS-263

Change-Id: Ib235c4b7af87007ba0d57f89ed79c80fb263eacd

Patchset: 4
http://review.cyanogenmod.org/#/c/106107/